# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 00:14
from __future__ import unicode_literals

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='location',
            field=location_field.models.plain.PlainLocationField(max_length=63, verbose_name='Coordinate'),
        ),
    ]
